#!/bin/bash

ROOT="$1"
FILE="$2"
COPY=$3
FLAGS=$4

FILE_NAME="${FILE%.*}"
FILE_DIR="`pwd`"

cd $ROOT

if [ ! -d tex-build ]; then mkdir tex-build; fi

cd tex-build

TEX_FILE="$FILE_NAME.tex"
PDF_FILE="$FILE_NAME.pdf"


for f in $(find "$FILE_DIR" -iname '*.tex' -or -iname '*.fmt');
do cp $f .; done


if [ "$COPY" = "t" ]
then cp "$FILE_DIR"/*.lhs .
     SRC="$FILE"
else SRC="$FILE_DIR/$FILE"
fi




lhs2TeX $FLAGS -o "$TEX_FILE" "$SRC" > /dev/null

latex -interaction=nonstopmode "$TEX_FILE"
pdflatex -synctex=1 -interaction=nonstopmode "$TEX_FILE"

PDF_TARGET="$FILE_DIR/$FILE.pdf"
cp "$PDF_FILE" "$PDF_TARGET"

