#!/bin/bash

ROOT="$1"
FILE="$2"
COPY=$3
FLAGS=$4

FILE_NAME="${FILE%.*}"
FILE_DIR="`pwd`"

cd $ROOT

if [ ! -d tex-build ]; then mkdir tex-build; fi


TEX_FILE="$FILE_NAME.tex"
PDF_FILE="$FILE_NAME.pdf"


function copyAll {
    for f in $(eval "find . $1")
    do  echo "Copying $f"
        cp --parents "$f" "$ROOT/tex-build"; done
}

cd "$FILE_DIR"

copyAll "-iname '*.tex' -or -iname '*.fmt'"


if [ "$COPY" = "t" ]
then echo "Copying *.lhs files from $FILE_DIR"
     copyAll "-iname '*.lhs'"
     SRC="$FILE"
else SRC="$FILE_DIR/$FILE"
fi


cd "$ROOT/tex-build"


lhs2TeX $FLAGS -o "$TEX_FILE" "$SRC" > /dev/null

latex -interaction=nonstopmode "$TEX_FILE"
pdflatex -synctex=1 -interaction=nonstopmode "$TEX_FILE"

PDF_TARGET="$FILE_DIR/$FILE.pdf"
cp "$PDF_FILE" "$PDF_TARGET"

